/**
 * Generic order deployment service.
 *
 * Fetches the .rain strategy file and shared settings.yaml from GitHub,
 * then builds a DotrainOrderGui instance for any strategy type and returns
 * DeploymentTransactionArgs ready for an EOA wallet or SAFE.
 *
 * All strategy-specific params (field values, token keys, deposit amounts)
 * come from the OrderConfig — add new strategy types purely in tokens.yaml.
 */

import { DotrainOrderGui } from "@rainlanguage/orderbook";
import type { DeploymentTransactionArgs } from "@rainlanguage/orderbook";
import type { OrderConfig } from "$lib/config/strategies";
import { REGISTRY_COMMIT } from "$lib/config/strategies";

const BASE_URL = `https://raw.githubusercontent.com/rainlanguage/rain.strategies/${REGISTRY_COMMIT}`;

// Cache raw text fetches so each file is only downloaded once per session
const fetchCache = new Map<string, Promise<string>>();

function fetchText(url: string): Promise<string> {
  if (!fetchCache.has(url)) {
    fetchCache.set(
      url,
      fetch(url).then((r) => {
        if (!r.ok) throw new Error(`Failed to fetch ${url}: ${r.statusText}`);
        return r.text();
      }),
    );
  }
  return fetchCache.get(url)!;
}

/**
 * Fetch the .rain file for a strategy type and the shared settings.yaml,
 * then instantiate a DotrainOrderGui for the given deployment key.
 */
async function buildGui(
  strategyType: string,
  deploymentKey: string,
): Promise<DotrainOrderGui> {
  const [dotrain, settings] = await Promise.all([
    fetchText(`${BASE_URL}/src/${strategyType}.rain`),
    fetchText(`${BASE_URL}/settings.yaml`),
  ]);

  const result = await DotrainOrderGui.newWithDeployment(
    dotrain,
    [settings],
    deploymentKey,
  );
  if (result.error) throw new Error(result.error.readableMsg);
  return result.value;
}

export interface DeploymentResult {
  label: string;
  composedRainlang: string;
  args: DeploymentTransactionArgs;
  /** Vault IDs resolved after deployment (auto-generated or from tokens.yaml). */
  vaultIds: Record<string, Record<string, string>>;
}

/**
 * Build deployment args for a single order.
 * Fully strategy-agnostic — driven entirely by the OrderConfig.
 */
export async function buildOrderDeployment(
  order: OrderConfig,
  ownerAddress: string,
): Promise<DeploymentResult> {
  const gui = await buildGui(order.strategyType, order.deploymentKey);

  for (const [key, address] of Object.entries(order.selectTokens)) {
    await gui.setSelectToken(key, address);
  }

  for (const [binding, value] of Object.entries(order.fieldValues)) {
    gui.setFieldValue(binding, value);
  }

  for (const [tokenKey, amount] of Object.entries(order.deposits)) {
    if (amount && amount !== "0") {
      gui.setDeposit(tokenKey, amount);
    }
  }

  // Set vault IDs (Rain "word IDs") when specified in tokens.yaml.
  // This ensures buy and sell orders within a strategy pair share the same vaults.
  if (order.vaultIds) {
    for (const [ioType, tokenVaults] of Object.entries(order.vaultIds)) {
      for (const [tokenKey, vaultId] of Object.entries(tokenVaults)) {
        const vaultResult = gui.setVaultId(
          ioType as "input" | "output",
          tokenKey,
          vaultId as `0x${string}`,
        );
        if (vaultResult?.error) {
          throw new Error(
            `Failed to set vault ID for ${ioType}.${tokenKey}: ${vaultResult.error.readableMsg}`,
          );
        }
      }
    }
  }

  const rainlangResult = await gui.getComposedRainlang();
  if (rainlangResult.error) throw new Error(rainlangResult.error.readableMsg);

  const argsResult = await gui.getDeploymentTransactionArgs(ownerAddress);
  if (argsResult.error) throw new Error(argsResult.error.readableMsg);

  // Retrieve resolved vault IDs (from tokens.yaml or auto-generated by GUI)
  const vaultIds: Record<string, Record<string, string>> = {};
  const vaultIdsResult = gui.getVaultIds();
  if (!vaultIdsResult?.error && vaultIdsResult?.value) {
    for (const [ioType, tokens] of vaultIdsResult.value) {
      vaultIds[ioType] = {};
      for (const [tokenKey, vaultId] of tokens) {
        if (vaultId !== undefined) vaultIds[ioType][tokenKey] = vaultId;
      }
    }
  }

  return {
    label: order.label,
    composedRainlang: rainlangResult.value,
    args: argsResult.value,
    vaultIds,
  };
}
